Feature: Unsuccessful Protection Operations For Various Combinations of User, Operation, Data Element and Bulk Input Data
    As a user of the appython module (installed via protegrity_developer_python)
    I want to verify protection operations fail for invalid, unauthorized and other negative cases
    So that I can ensure errors are handled correctly and data security is not compromised

    Background:
        Given the appython module is available via the protegrity_developer_python installation
        And the enviroment variables DEV_EDITION_EMAIL, DEV_EDITION_PASSWORD and DEV_EDITION_API_KEY are set
        And a policy is deployed with required data elements, users and permissions required to test the scenario

    @tokenization @bulk @string @negative @PDE-96
    Scenario Outline: Validate error message on input data access (list of strings) with user having no appropriate permisions
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user           | data_element | input_data                                                                                                      | result    | output                                                                        | error_message                                                                             | error_codes  |
            | protect   | finance        | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | marketing      | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | hr             | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | robin.goodwill | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | finance        | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | hr             | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | merlin.ishida  | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | finance        | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | hr             | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | marketing      | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | paloma.torres  | city         | ["Springfield", "Shelbyville", "Capital City", "Smalltown"]                                                     | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | unprotect | admin          | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | None      | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                        | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | admin          | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | None      | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"] | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | admin          | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | None      | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | None      | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                        | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | None      | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"] | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | None      | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | jay.banerjee   | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | None      | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                        | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | paloma.torres  | datetime     | ["2023-09-04T14:30:00", "2022-08-05T10:15:00", "0600-01-01 00:00:00 000", "1970-04-02 07:00:58 369000"]         | None      | [None, None, None, None]                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | paloma.torres  | nin          | ["QQ123456C", "CD654321E", "EF112233A", "GH445566B"]                                                            | None      | [None, None, None, None]                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | merlin.ishida  | address      | ["123 Main St, Springfield", "456 Elm St, Shelbyville", "789 Oak Ave, Capital City", "101 Maple Rd, Smalltown"] | None      | [None, None, None, None]                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | merlin.ishida  | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | None      | [None, None, None, None]                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | admin          | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                                    | None      | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                  | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | int          | ["12335", "67890", "23456", "78901"]                                                                            | None      | ["12335", "67890", "23456", "78901"]                                          | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | jay.banerjee   | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                                    | None      | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                  | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | paloma.torres  | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                                    | None      | [None, None, None, None]                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | merlin.ishida  | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                                    | None      | [None, None, None, None]                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | admin          | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | ["X1234567", "Y7654321", "A1122334", "B4455667"]                              | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | ["X1234567", "Y7654321", "A1122334", "B4455667"]                              | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | jay.banerjee   | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | ["X1234567", "Y7654321", "A1122334", "B4455667"]                              | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | paloma.torres  | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | [None, None, None, None]                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | merlin.ishida  | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | [None, None, None, None]                                                      | None                                                                                      | (8, 8, 8, 8) |

    @tokenization @bulk @string @negative @PDE-96
    Scenario Outline: Validate error message on input data access (tuple of strings) with user having no appropriate permisions
        When the user performs "<operation>" operation using "tokenization" method on the "tuple of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user           | data_element | input_data                                                                                                      | result    | output                                                                        | error_message                                                                             | error_codes  |
            | protect   | finance        | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | marketing      | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | hr             | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | robin.goodwill | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | finance        | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | hr             | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | merlin.ishida  | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | finance        | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | hr             | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | marketing      | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | protect   | paloma.torres  | city         | ["Springfield", "Shelbyville", "Capital City", "Smalltown"]                                                     | exception | None                                                                          | 3, The user does not have the appropriate permissions to perform the requested operation. | None         |
            | unprotect | admin          | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | None      | ("John Doe", "Jane Smith", "Alice Johnson", "Bob Lee")                        | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | admin          | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | None      | ("4111111122223333", "5500000000000004", "340000000000009", "30000000000004") | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | admin          | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | None      | ("SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA")                                | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | None      | ("John Doe", "Jane Smith", "Alice Johnson", "Bob Lee")                        | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | None      | ("4111111122223333", "5500000000000004", "340000000000009", "30000000000004") | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | postcode     | ["SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA"]                                                                  | None      | ("SW1A 1AA", "W1A 0AX", "EC1A 1BB", "GIR 0AA")                                | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | jay.banerjee   | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                          | None      | ("John Doe", "Jane Smith", "Alice Johnson", "Bob Lee")                        | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | paloma.torres  | datetime     | ["2023-09-04T14:30:00", "2022-08-05T10:15:00", "0600-01-01 00:00:00 000", "1970-04-02 07:00:58 369000"]         | None      | (None, None, None, None)                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | paloma.torres  | nin          | ["QQ123456C", "CD654321E", "EF112233A", "GH445566B"]                                                            | None      | (None, None, None, None)                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | merlin.ishida  | address      | ["123 Main St, Springfield", "456 Elm St, Shelbyville", "789 Oak Ave, Capital City", "101 Maple Rd, Smalltown"] | None      | (None, None, None, None)                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | merlin.ishida  | ccn          | ["4111111122223333", "5500000000000004", "340000000000009", "30000000000004"]                                   | None      | (None, None, None, None)                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | admin          | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                                    | None      | ("123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666")                  | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | int          | ["12335", "67890", "23456", "78901"]                                                                            | None      | ("12335", "67890", "23456", "78901")                                          | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | jay.banerjee   | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                                    | None      | ("123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666")                  | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | paloma.torres  | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                                    | None      | (None, None, None, None)                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | merlin.ishida  | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                                    | None      | (None, None, None, None)                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | admin          | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | ("X1234567", "Y7654321", "A1122334", "B4455667")                              | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | devops         | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | ("X1234567", "Y7654321", "A1122334", "B4455667")                              | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | jay.banerjee   | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | ("X1234567", "Y7654321", "A1122334", "B4455667")                              | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | paloma.torres  | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | (None, None, None, None)                                                      | None                                                                                      | (8, 8, 8, 8) |
            | unprotect | merlin.ishida  | passport     | ["X1234567", "Y7654321", "A1122334", "B4455667"]                                                                | None      | (None, None, None, None)                                                      | None                                                                                      | (8, 8, 8, 8) |

    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect with user not present in policy for list of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output                   | error_message                                                                             |
            | protect   | dummyUser | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]       | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser | int          | ["12335", "67890", "23456", "78901"]                         | None      | [None, None, None, None] | None                                                                                      |
            | reprotect | dummyUser | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"] | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |

    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect with user not present in policy for tuple of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "tuple of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output                   | error_message                                                                             |
            | protect   | dummyUser | name         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]       | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser | int          | ["12335", "67890", "23456", "78901"]                         | None      | (None, None, None, None) | None                                                                                      |
            | reprotect | dummyUser | ssn          | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"] | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |

    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect with data element not present in policy for list of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output | error_message                                         |
            | protect   | superuser | dummyDE      | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]       | exception | None   | 2, The data element could not be found in the policy. |
            | unprotect | superuser | dummyDE      | ["12335", "67890", "23456", "78901"]                         | exception | None   | 2, The data element could not be found in the policy. |
            | reprotect | superuser | dummyDE      | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"] | exception | None   | 2, The data element could not be found in the policy. |

    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect with data element not present in policy for tuple of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "tuple of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output | error_message                                         |
            | protect   | superuser | dummyDE      | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]       | exception | None   | 2, The data element could not be found in the policy. |
            | unprotect | superuser | dummyDE      | ["12335", "67890", "23456", "78901"]                         | exception | None   | 2, The data element could not be found in the policy. |
            | reprotect | superuser | dummyDE      | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"] | exception | None   | 2, The data element could not be found in the policy. |

    @tokenization @bulk @string @negative @PDE-97
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing invalid list of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                                                                                                                                                                                                                                                                                                                               | result    | output                                                                                  | error_message                                   | error_codes      |
            | protect   | superuser | email        | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | email        | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | email        | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | email        | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | email        | ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaQ@example.coma", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbQ@example.comb", "ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccQ@example.comc", "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ@example.comd"] | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | ccn          | ["aA1", "bB2", "cC3", "dD4"]                                                                                                                                                                                                                                                                                                             | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | ccn          | ["4111111122223333", "bB2", "4111111122223333", "dD4"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | ccn          | ["aA1", "bB2", "cC3", "dD4"]                                                                                                                                                                                                                                                                                                             | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | ccn          | ["aA1", "bB2", "cC3", "dD4"]                                                                                                                                                                                                                                                                                                             | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | int          | ["abcdef", "ghijkl", "mnopqr", "stuvwx"]                                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | int          | ["abcdef", "ghijkl", "mnopqr", "stuvwx"]                                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | int          | ["abcdef", "ghijkl", "mnopqr", "stuvwx"]                                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | datetime     | ["1906-12-02 13:11:09 4004453117", "1907-01-01 00:00:00 000", "1908-02-02 02:02:02 222", "1909-03-03 03:03:03 333"]                                                                                                                                                                                                                      | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | datetime     | ["1906-12-02 13:11:09 4004453117", "1907-01-01 00:00:00 000", "1908-02-02 02:02:02 222", "1909-03-03 03:03:03 333"]                                                                                                                                                                                                                      | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | datetime     | ["1906-12-02 13:11:09 4004453117", "1907-01-01 00:00:00 000", "1908-02-02 02:02:02 222", "1909-03-03 03:03:03 333"]                                                                                                                                                                                                                      | None      | [None, '1907-01-01 00:00:00 000', '1908-02-02 02:02:02 222', '1909-03-03 03:03:03 333'] | None                                            | (50, 50, 50, 50) |
            | protect   | superuser | datetime     | ["1906:12:02", "1907:01:03", "1908:02:04", "1909:03:05"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | datetime     | ["1906:12:02", "1907:01:03", "1908:02:04", "1909:03:05"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | datetime     | ["1906:12:02", "1907/01/03", "1908:02:04", "1909-03-05"]                                                                                                                                                                                                                                                                                 | None      | [None, '1907/01/03', None, '1909-03-05']                                                | None                                            | (50, 50, 50, 50) |
            | protect   | superuser | datetime     | ["12/02/1999", "13/03/2000", "14/04/2001", "15/05/2002"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | datetime     | ["12/02/1999", "13/03/2000", "14/04/2001", "15/05/2002"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | datetime     | ["12/02/1999", "13/03/2000", "14/04/2001", "15/05/2002"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                    | 44, The content of the input data is not valid. | None             |

    @tokenization @bulk @bytes @negative @PDE-97 @PDE-123
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing invalid tuple of bytes input data
        When the user performs "<operation>" operation using "tokenization" method on the "tuple of bytes" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                                                                                                                                                                                                                                                                                                                               | result    | output                                                                                     | error_message                                   | error_codes      |
            | protect   | superuser | email        | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | email        | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | email        | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | email        | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | email        | ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaQ@example.coma", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbQ@example.comb", "ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccQ@example.comc", "ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddQ@example.comd"] | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | ccn          | ["aA1", "bB2", "cC3", "dD4"]                                                                                                                                                                                                                                                                                                             | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | ccn          | ["4111111122223333", "bB2", "4111111122223333", "dD4"]                                                                                                                                                                                                                                                                                   | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | ccn          | ["aA1", "bB2", "cC3", "dD4"]                                                                                                                                                                                                                                                                                                             | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | ccn          | ["aA1", "bB2", "cC3", "dD4"]                                                                                                                                                                                                                                                                                                             | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | int          | ["abcdef", "ghijkl", "mnopqr", "stuvwx"]                                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | int          | ["abcdef", "ghijkl", "mnopqr", "stuvwx"]                                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | int          | ["abcdef", "ghijkl", "mnopqr", "stuvwx"]                                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | protect   | superuser | datetime     | ["1906-12-02 13:11:09 4004453117", "1907-01-01 00:00:00 000", "1908-02-02 02:02:02 222", "1909-03-03 03:03:03 333"]                                                                                                                                                                                                                      | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | datetime     | ["1906-12-02 13:11:09 4004453117", "1907-01-01 00:00:00 000", "1908-02-02 02:02:02 222", "1909-03-03 03:03:03 333"]                                                                                                                                                                                                                      | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | datetime     | ["1906-12-02 13:11:09 4004453117", "1907-01-01 00:00:00 000", "1908-02-02 02:02:02 222", "1909-03-03 03:03:03 333"]                                                                                                                                                                                                                      | None      | (None, b'1907-01-01 00:00:00 000', b'1908-02-02 02:02:02 222', b'1909-03-03 03:03:03 333') | None                                            | (50, 50, 50, 50) |
            | protect   | superuser | datetime     | ["1906:12:02", "1907:01:03", "1908:02:04", "1909:03:05"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | datetime     | ["1906:12:02", "1907:01:03", "1908:02:04", "1909:03:05"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | datetime     | ["1906:12:02", "1907/01/03", "1908:02:04", "1909-03-05"]                                                                                                                                                                                                                                                                                 | None      | (None, b'1907/01/03', None, b'1909-03-05')                                                 | None                                            | (50, 50, 50, 50) |
            | protect   | superuser | datetime     | ["12/02/1999", "13/03/2000", "14/04/2001", "15/05/2002"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | unprotect | superuser | datetime     | ["12/02/1999", "13/03/2000", "14/04/2001", "15/05/2002"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |
            | reprotect | superuser | datetime     | ["12/02/1999", "13/03/2000", "14/04/2001", "15/05/2002"]                                                                                                                                                                                                                                                                                 | exception | None                                                                                       | 44, The content of the input data is not valid. | None             |

    @tokenization @bulk @integer @negative @PDE-97
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing invalid list of integers input data
        When the user performs "<operation>" operation using "tokenization" method on the "list of integers" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                                                   | result    | output | error_message                                   | error_codes |
            | protect   | superuser | int          | ["12345", "-4147483648", "-1", "-4147483648"]                | exception | None   | 44, The content of the input data is not valid. | None        |
            | unprotect | superuser | int          | ["4147483648", "4147483648", "4147483648", "0"]              | exception | None   | 44, The content of the input data is not valid. | None        |
            | reprotect | superuser | int          | ["10147483648", "10147483648", "10147483648", "10147483648"] | exception | None   | 44, The content of the input data is not valid. | None        |

    @tokenization @bulk @string @negative @PDE-124 @skip
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing list of strings input data of more than valid max length
        When the user performs "<operation>" operation using "tokenization" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                             | result    | output | error_message                                     | error_codes |
            | protect   | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |

    @tokenization @bulk @bytes @negative @PDE-124 @skip
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing tuple of bytes input data of more than valid max length
        When the user performs "<operation>" operation using "tokenization" method on the "tuple of bytes" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>", output as "<output>" and error codes as "<error_codes>"
        Examples:
            | operation | user      | data_element | input_data                             | result    | output | error_message                                     | error_codes |
            | protect   | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | protect   | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | unprotect | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | name         | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | city_de      | InputDataMoreThan_4096_CodePoints_Bulk | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | address      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | zipcode      | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | email        | InputDataMoreThan_256_Bytes_Bulk       | exception | None   | 23, Data is too long to be protected/unprotected. | None        |
            | reprotect | superuser | ccn          | InputDataMoreThan_4096_Bytes_Bulk      | exception | None   | 23, Data is too long to be protected/unprotected. | None        |

    @tokenization @bulk @integer @negative @PDE-122
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect on passing unsupported data type for data element that supports only string data type (list of integers input data)
        When the user performs "<operation>" operation using "tokenization" method on the "list of integers" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                | result    | output | error_message                                                                  |
            | protect   | superuser | address      | [12456, 1234, 1234, 1234] | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |
            | unprotect | superuser | address      | [12456, 1234, 1234, 1234] | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |
    # | reprotect | superuser | address      | [12456, 1234, 1234, 1234] | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |

    @tokenization @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect using encryption data element without passing encrypt_to parameter in the API call for tuple of strings input data
        When the user performs "<operation>" operation using "tokenization" method on the "tuple of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user      | data_element | input_data                                             | result    | output | error_message                                                                  |
            | protect   | superuser | text         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"] | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |
            | unprotect | superuser | text         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"] | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |
            | reprotect | superuser | text         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"] | exception | None   | 26, Unsupported algorithm or unsupported action for the specific data element. |

    @encryption @bulk @string @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect using data element of type encryption for various negative scenarios with list of strings input data
        When the user performs "<operation>" operation using "encryption" method on the "list of strings" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user          | data_element | input_data                                                                       | result    | output                   | error_message                                                                             |
            | protect   | finance       | text         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                           | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | finance       | text         | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                     | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | jay.banerjee  | text         | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                     | None      | [None, None, None, None] | None                                                                                      |
            | unprotect | paloma.torres | text         | ["2023-09-04", "2023-09-04", "2023-09-04", "2023-09-04"]                         | None      | [None, None, None, None] | None                                                                                      |
            | protect   | dummyUser     | text         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                           | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser     | text         | ["SGVsbG8sIEpvIQ==", "SGVsbG8sIEpvIQ==", "SGVsbG8sIEpvIQ==", "SGVsbG8sIEpvIQ=="] | None      | [None, None, None, None] | None                                                                                      |
            | reprotect | dummyUser     | text         | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                     | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |

    @encryption @bulk @bytes @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect using data element of type encryption for various negative scenarios with list of bytes input data
        When the user performs "<operation>" operation using "encryption" method on the "list of bytes" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user          | data_element | input_data                                                                                   | result    | output                   | error_message                                                                             |
            | protect   | finance       | text         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                       | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | protect   | finance       | text         | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                 | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | jay.banerjee  | text         | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                 | None      | [None, None, None, None] | None                                                                                      |
            | unprotect | paloma.torres | text         | ["2023-09-04T14:30:00", "2023-09-05T14:30:00", "2023-09-06T14:30:00", "2023-09-07T14:30:00"] | None      | [None, None, None, None] | None                                                                                      |
            | protect   | dummyUser     | text         | ["John Doe", "Jane Smith", "Alice Johnson", "Bob Lee"]                                       | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser     | text         | ["12345", "67890", "23456", "78901"]                                                         | None      | [None, None, None, None] | None                                                                                      |
            | reprotect | dummyUser     | text         | ["123-45-6789", "987-65-4321", "111-22-3333", "444-55-6666"]                                 | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |

    @encryption @bulk @integer @negative
    Scenario Outline: Validate error message on performing protect/unprotect/reprotect using data element of type encryption for various negative scenarios with tuple of integers input data
        When the user performs "<operation>" operation using "encryption" method on the "tuple of integers" input data "<input_data>" using "<data_element>" data element with the username "<user>"
        Then the result is "<result>", the error message should be "<error_message>" and output as "<output>"
        Examples:
            | operation | user          | data_element | input_data                       | result    | output                   | error_message                                                                             |
            | protect   | finance       | text         | ["1234", "1234", "1234", "1234"] | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | jay.banerjee  | text         | ["1234", "1234", "1234", "1234"] | None      | (None, None, None, None) | None                                                                                      |
            | unprotect | paloma.torres | text         | ["1234", "1234", "1234", "1234"] | None      | (None, None, None, None) | None                                                                                      |
            | protect   | dummyUser     | text         | ["1234", "1234", "1234", "1234"] | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |
            | unprotect | dummyUser     | text         | ["1234", "1234", "1234", "1234"] | None      | (None, None, None, None) | None                                                                                      |
            | reprotect | dummyUser     | text         | ["1234", "1234", "1234", "1234"] | exception | None                     | 3, The user does not have the appropriate permissions to perform the requested operation. |